apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-node-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: second-node-app
    spec:
      containers:
        - name: second-node-container
          image:
