apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-node-app
      tier: backend
    # matchExpressions:
    #   - { key: app, operator: In, values: [second-node-app, first-node-app] }
  template:
    metadata:
      labels:
        app: second-node-app
        tier: backend
    spec:
      containers:
        - name: second-node-container
          image: jorge107/second-node-image:v1
